### PR TITLE
Fix BRPop infinite blocking

### LINKED ISSUE #314: BRPop: Never returns (sometimes) even if the queue has data
Hello @siddontang
I get this weird issue that sometimes my app can not pop any more objects from a ledis list even if the queue is full. 

I embed ledis into the app, by starting a ledis app, and then internally access the database directly. I created a gist [here](https://gist.github.com/muhamadazmy/cfca4d37b111f6beb23925d2369b384c) that has a similar structure with my app, and at the same time produces the issue.

When u run this gist, the counter will keep counting up until some random point it will block and never increase again, if u try to connect with an external redis client (I use redis-cli) to port 7000 and check the length of the queue, u will see that it keeps growing up, and also u can do BRPop normally, it's only the code inside the app what blocks.

Thanks.

### PR DESCRIPTION
**Pull request by muhamadazmy**
Fixes #314

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @muhamadazmy 

But CI failed, I have to see why causes the failure.

**Comment by siddontang** [comment]
@muhamadazmy 

The failed CI may be caused by https://github.com/siddontang/ledisdb/blob/master/ledis/t_list_test.go#L218

Even we sleep for 100ms, the goroutine may still be not started yet because travis CI is slow. Can you enlarge the sleep time, like 1 second, to see whether we can pass the CI or not.

**Comment by muhamadazmy** [comment]
@siddontang sorry for late response, i have must missed that you have commented back. 

I tried this out and rerun the test locally and it also did not work. I still got a test timeout.

**Comment by muhamadazmy** [comment]
@siddontang I did some refactoring on the logic to avoid the race condition by implementing an atomic "popOrWait" method. 

Also I used context instead of channel since they are much easier to use for signalling jobs (u can see from amount of code removed)

**Comment by muhamadazmy** [comment]
Sorry, don't merge yet. it seems this reproduce the original bug. I get random indefinite blocking again.

File: ledis/t_list.go [hunk 1]
```diff
@@ -11,6 +11,7 @@ import (
 	"github.com/siddontang/go/log"
 	"github.com/siddontang/go/num"
 	"github.com/siddontang/ledisdb/store"
+	"golang.org/x/net/context"
```
Comment (siddontang) [inline ledis/t_list.go]: I prefer using go context directly.

Btw, we can upgrade go verion in traivs CI too.

**Comment by siddontang** [comment]
Thanks @muhamadazmy 

I will see it.

File: ledis/t_list.go [hunk 2]
```diff
@@ -692,64 +693,39 @@ func (db *DB) LKeyExists(key []byte) (int64, error) {
...
 
-	deadT := time.Now().Add(timeout)
+		for _, key := range keys {
+			v, err := db.lbkeys.popOrWait(db, key, whereSeq, cancel)
 
-	for {
-		if timeout == 0 {
-			key := <-ch
-			if v, err := db.lpop(key, whereSeq); err != nil {
+			if err != nil {
```
Comment (siddontang) [inline ledis/t_list.go]: if we get the item or meet error, we should cancel the context when return to avoid the resource leak.

File: ledis/t_list.go [hunk 3]
```diff
@@ -692,64 +693,39 @@ func (db *DB) LKeyExists(key []byte) (int64, error) {
...
-					continue
-				} else {
-					return []interface{}{key, v}, nil
-				}
-			case <-time.After(d):
-				return nil, nil
-			}
 		}
 
+		err := func() error {
```
Comment (siddontang) [inline ledis/t_list.go]: I am confused with this, why not using 
```
<-ctx.Done()
cancel()
err = ctx.Err()
```

direclty?

Comment (muhamadazmy) [inline ledis/t_list.go]: Good point :)

**Comment by muhamadazmy** [comment]
Also if u run the gist that is attached to the issue u will see that it blocks again :( I don't know why, and it happens in the listBatch lock method for some reason. And i found that it even blocks the push.

I couldn't figure out why, so if u may look at it if u like the refactoring i made.

**Comment by siddontang** [comment]
ok @muhamadazmy 
I will try it later. :-)

File: ledis/t_list.go (hunk 2 above)
Comment (muhamadazmy) [inline ledis/t_list.go]: done

File: ledis/t_list.go [hunk 4]
```diff
@@ -692,72 +693,42 @@ func (db *DB) LKeyExists(key []byte) (int64, error) {
...
-				return nil, nil
-			}
 		}
 
+		//blocking wait
+		<-ctx.Done()
+
+		//if ctx.Err() is a deadline exceeded (timeout) we return
+		//otherwise we try to pop one of the keys again.
+		if ctx.Err() == context.DeadlineExceeded {
```
Comment (siddontang) [inline ledis/t_list.go]: here we must also call cancel to avoid the resource leak.

**Comment by siddontang** [comment]
CI still failed :sob:

**Comment by siddontang** [comment]
Hi @muhamadazmy 

I find the reason of the failed test, you can't call lock and unlock at the beginning of the function popOrWait, which may cause deadlock, a better way is:

```
func (l *lBlockKeys) popOrWait(db *DB, key []byte, whereSeq int32, fn context.CancelFunc) ([]interface{}, error) {
	v, err := db.lpop(key, whereSeq)
	if err != nil {
		return nil, err
	} else if v != nil {
		return []interface{}{key, v}, nil
	}

	l.Lock()
 
	s := hack.String(key)
	chs, ok := l.keys[s]
	if !ok {
		chs = list.New()
		l.keys[s] = chs
	}

	chs.PushBack(fn)
        l.Unlock()
	return nil, nil
}
```

**Comment by siddontang** [comment]
Thanks @muhamadazmy 

I think we can remove "golang.org/x/net/context" and use standard context library directly. 

And we should update the go version in travis CI, maybe  1.8 is fine.

**Comment by muhamadazmy** [comment]
Thanks @siddontang for merging this in. 

We can definitely upgrade context to the standard lib one, except i didn't want to break compatibility with 1.6 version. Also i noticed context package is used in other parts of ledisd. Should we upgrade all or just this part ?

**Comment by siddontang** [comment]
Thanks @muhamadazmy 

Now the lua vendor also uses the context, we can still use it, no need to upgrade now.
